

services:
  web:
    build: .
    container_name: lagos_app
    ports:
      - "8080:80"   # 8080 sur ton PC â†’ 80 dans le conteneur
    volumes:
      - ./:/var/www/html   # pour synchroniser ton code local avec le conteneur
    networks:
      - monreseau

  db:
    image: mysql:8.0
    container_name: lagos_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: lagos
      MYSQL_USER: lagos
      MYSQL_PASSWORD: W3a9ClHrgC[krsrd
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - monreseau

networks:
  monreseau:

volumes:
  db_data:
