services:
  web:
    build: .
    container_name: lagos_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - monreseau

  db:
    image: mysql:8.0
    container_name: lagos_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: lagos
      MYSQL_USER: lagos
      MYSQL_PASSWORD: W3a9ClHrgC[krsrd
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - monreseau

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"   
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - monreseau

networks:
  monreseau:

volumes:
  db_data:
  jenkins_home:
